MyDuoCards/Controllers/OptionsController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyDuoCards.Models;
using MyDuoCards.Models.DBModels;
using MyDuoCards.Models.Extensions;
using MyDuoCards.Models.ViewModels;

namespace MyDuoCards.Controllers
{
    [Authorize]
	public class OptionsController : Controller
	{
		private readonly ApplicationContext _context;

		public OptionsController(ApplicationContext context) { 
			_context = context;
		}

		public async Task<IActionResult> Index()
		{
			var user = await _context.Users.Where(u => u.Login == User.Identity.Name)
                .Include(u => u.Role)
                .SingleOrDefaultAsync();

            EditUserModel userForView = new EditUserModel
            {
                Login = user.Login,
                Email = user.Email,
                RoleName = user.Role.Name,
                Password = user.Password,
                RoleId = user.RoleId
            };

            return View(userForView);
		}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Login,Email,RoleName,Password,ConfirmPassword,RoleId")] EditUserModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _context.Users
                    .Where(u => u.Login == User.Identity!.Name)
                    .Include(u => u.Role)
                    .SingleOrDefaultAsync();

                if (user == null)
                {
                    ModelState.AddModelError("EdittingError", "User not found");
                    return View(model);
                }

                if (user.Login != model.Login && await _context.Users.AnyAsync(u => u.Login == model.Login))
                {
                    ModelState.AddModelError("EdittingError", "Login already exists");
                    return View(model);
                }

                if (user.Email != model.Email && await _context.Users.AnyAsync(u => u.Email == model.Email))
                {
                    ModelState.AddModelError("EdittingError", "Email already exists");
                    return View(model);
                }

                user.Login = model.Login;
                user.Email = model.Email;

                if (!string.IsNullOrEmpty(model.Password) && model.Password != model.ConfirmPassword)
                {
                    ModelState.AddModelError("EdittingError", "Passwords do not match");
                    return View(model);
                }

                if (!string.IsNullOrEmpty(model.Password) && user.Password != model.Password)
                {
                    user.Password = model.Password.ToHash();
                }

                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();

                    await HttpContext.SignInAsync(user.ClaimCreator());

                    return RedirectToAction("Index", "Home");
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
            }

            return View(model);
        }

    }
}

MyDuoCards/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyDuoCards.Models;
using MyDuoCards.Models.DBModels;

namespace MyDuoCards.Controllers
{
    public class RolesController : Controller
    {
        private readonly ApplicationContext _context;

        public RolesController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
              return _context.Roles != null ? 
                          View(await _context.Roles.ToListAsync()) :
                          Problem("Entity set 'ApplicationContext.Roles'  is null.");
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Roles == null)
            {
                return Problem("Entity set 'ApplicationContext.Roles'  is null.");
            }
            var role = await _context.Roles.FindAsync(id);
            if (role != null)
            {
                _context.Roles.Remove(role);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
          return (_context.Roles?.Any(e => e.RoleId == id)).GetValueOrDefault();
        }
    }
}

MyDuoCards/Controllers/VocabularyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MyDuoCards.Models;
using MyDuoCards.Models.DBModels;
using MyDuoCards.Models.Extensions;
using MyDuoCards.Models.ViewModels;
using System.Diagnostics;
using System.Security.Policy;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace MyDuoCards.Controllers
{
    [Authorize]
    public class VocabularyController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationContext _context;
        private int amountOfElements = Constants.AmountOfCardsVocabulary;

        public VocabularyController(ILogger<HomeController> logger, ApplicationContext context)
        {
            _logger = logger;
            _context = context;
        }


		public async Task<IActionResult> Index(string? searchString, int page = 1)
        {
            ViewData["searchString"] = searchString;
			ViewData["page"] = page;

			var modelRu = _context.RuWords
					.Include(ruWord => ruWord.EnWord)
						.ThenInclude(enWord => enWord!.Dictionaries!)
							.ThenInclude(dict => dict.User);


			var modelRuPlus = new List<RuWord>();

			if (!String.IsNullOrEmpty(searchString))
			{
				if (LanguageValidator.IsRussian(searchString))
				{
					modelRuPlus = await modelRu
						.Where(ruWord => ruWord.RuWriting.Contains(searchString))
					.ToListAsync();

				}
				else if (searchString.IsEnglish())
				{
					modelRuPlus = await modelRu
						.Where(ruWord => ruWord.EnWord!.EnWriting.Contains(searchString))
					.ToListAsync();
				}

			}
			else modelRuPlus = await modelRu.ToListAsync();

			var viewModel = modelRuPlus
				.Skip((page - 1) * amountOfElements)
				.Take(amountOfElements);

			var count = modelRuPlus.Count();

			List<int> list = null;
			if (count != 0)
			{
				int maxIndex = (count / amountOfElements);
                if (count % amountOfElements != 0) maxIndex++;
                list = ListBuilderForButtons.GetButtonIndexes(page, maxIndex);
			}
			ViewData["list"] = list;


			return View(viewModel);
        }

		public async Task<IActionResult> AddTheDictionary(int id)
		{
			var ruWord = await _context.RuWords.FindAsync(id);

			var user = await _context.Users
				.SingleOrDefaultAsync(u => u.Login == User.Identity!.Name);

			Random rand = new Random();
			_context.Dictionaries.Add(new Dictionary()
			{
				UserId = user.Id,
				EnWordId = ruWord.EnWordId,
				DictionaryStatementId = rand.Next(_context.DictionaryStatements.Count()) + 1
			});
			await _context.SaveChangesAsync();

			var previousPageUrl = Request.Headers["Referer"].ToString();
			return Redirect(previousPageUrl);
		}


		public async Task<IActionResult> RemoveDictionary(int id)
		{
			var ruWord = _context.RuWords
				.Include(ruWord => ruWord.EnWord)
				.Where(w => w.Id == id)
				.SingleOrDefault();

			var user = await _context.Users
				.Include(u => u.Dictionaries!)
					.ThenInclude(d => d.EuWord)
				.SingleOrDefaultAsync(u => u.Login == User.Identity!.Name);

			var dictToRemove = user!.Dictionaries!.Where(dict => dict.EuWord!.Id == ruWord!.EnWord!.Id).SingleOrDefault();

			_context.Dictionaries.Remove(dictToRemove);

			await _context.SaveChangesAsync();

			var previousPageUrl = Request.Headers["Referer"].ToString();
			return Redirect(previousPageUrl);
		}
	}
}

MyDuoCards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyDuoCards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/glassmorfic.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyDuoCards.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Login">MyDuoCards</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity!.IsAuthenticated)
                {
                    <div class="collapse navbar-collapse" id="navbarColor02">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">
                                    Home
                                    <span class="visually-hidden">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Vocabulary" asp-action="Index">
                                    Vocabulary
                                    <span class="visually-hidden">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Options" asp-action="Index">
                                    Options
                                    <span class="visually-hidden">(current)</span>
                                </a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop4" style="">
                                            <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Roles" asp-action="Index">Roles</a>
                                            <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
                                            <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Dictionaries" asp-action="Index">Dictionaries</a>
                                            <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="DictionaryStatements" asp-action="Index">Dictionary Statements</a>
                                            <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="EnWords" asp-action="Index">English Words</a>
                                            <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="RuWords" asp-action="Index">Russian Words</a>
                                        </div>
                                </li>
                            }
                            <li class="nav-item" style="margin-top: auto; margin-bottom: auto;">
                                <h5 class="text-success" style="margin: auto 10px">Your attendance streak:</h5>
                            </li>
                            <li class="nav-item" id="LastAttendance" style="margin-top: auto; margin-bottom: auto;">
                                <h5 class="text-success" style="margin: auto 0px">Loading</h5>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>

    <br></br>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark" data-bs-theme="dark">
        <div class="container">
            &copy; 2023 - MyDuoCards - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @if (User.Identity!.IsAuthenticated)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                $.ajax({
                    type: "GET",
                    url: "/Home/AttendanceGET",
                    dataType: "json",
                    success: function (data) {
                        if (data) {
                            //alert(typeof(data));
                            console.log("success!");
                            $('#LastAttendance').empty();
                            var h5Element = $('<h5>').text(data).attr('style', 'margin: auto 0px').addClass('text-success');
                            $('#LastAttendance').append(h5Element);
                        } else {
                            console.log('No attendance data available');
                        }
                    },
                    error: function (xhr) {
                        alert(xhr.status + ' Ошибка');
                    }
                });

                $.ajax({
                    type: "POST",
                    url: "/Home/AttendancePOST",
                    success: function () {
                        console.log("Attendance successfully posted");
                    },
                    error: function (xhr) {
                        console.error('Failed to post attendance: ' + xhr.status);
                    }
                });
            });
        </script>
    }



</body>
</html>